#!/bin/bash

###############################################################################
# Hermes Auto-Checklist - Runs at session start
# Purpose: Verify system health, report status, identify blocking issues
# Owner: Maxima
###############################################################################

set -e

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
LOG_DIR="$HOME/.hermes/logs"
REPORT_FILE="$LOG_DIR/session-start-$(date '+%Y%m%d-%H%M%S').md"

# Ensure log directory exists
mkdir -p "$LOG_DIR"

echo "🔍 Hermes Session Start Checklist"
echo "=================================="
echo "Timestamp: $TIMESTAMP"
echo ""

cat > "$REPORT_FILE" << EOF
# Hermes Session Start Report
**Time:** $TIMESTAMP

## 🌐 Site Status
EOF

# Check site 1: shemalewiki.online
if curl -s -o /dev/null -w "%{http_code}" https://shemalewiki.online | grep -q "200"; then
    echo "✅ shemalewiki.online: ONLINE (200)"
    echo "✅ shemalewiki.online: ONLINE (200)" >> "$REPORT_FILE"
else
    echo "❌ shemalewiki.online: OFFLINE"
    echo "❌ shemalewiki.online: OFFLINE" >> "$REPORT_FILE"
fi

# Check site 2: buscatrans.com
if curl -s -o /dev/null -w "%{http_code}" https://buscatrans.com | grep -q "200"; then
    echo "✅ buscatrans.com: ONLINE (200)"
    echo "✅ buscatrans.com: ONLINE (200)" >> "$REPORT_FILE"
else
    echo "❌ buscatrans.com: OFFLINE"
    echo "❌ buscatrans.com: OFFLINE" >> "$REPORT_FILE"
fi

echo ""
cat >> "$REPORT_FILE" << EOF

## 📦 Build Status
EOF

# Last build status
if [ -f "$LOG_DIR/last-build.txt" ]; then
    LAST_BUILD=$(cat "$LOG_DIR/last-build.txt")
    echo "Last build: $LAST_BUILD"
    echo "Last build: $LAST_BUILD" >> "$REPORT_FILE"
else
    echo "No build history found"
    echo "No build history found" >> "$REPORT_FILE"
fi

echo ""
cat >> "$REPORT_FILE" << EOF

## 🚀 Deploy Status
EOF

# Last deploy status
if [ -f "$LOG_DIR/last-deploy.txt" ]; then
    LAST_DEPLOY=$(cat "$LOG_DIR/last-deploy.txt")
    echo "Last deploy: $LAST_DEPLOY"
    echo "Last deploy: $LAST_DEPLOY" >> "$REPORT_FILE"
else
    echo "No deploy history found"
    echo "No deploy history found" >> "$REPORT_FILE"
fi

echo ""
cat >> "$REPORT_FILE" << EOF

## 📊 KPIs
EOF

# Database stats (requires Supabase connection)
echo "Database KPIs:"
echo "- Total profiles: [querying...]"
echo "- Profiles without photos: [querying...]"
echo "- New profiles today: [querying...]"

echo "Database KPIs:" >> "$REPORT_FILE"
echo "- Total profiles: [requires Supabase]" >> "$REPORT_FILE"
echo "- Profiles without photos: [requires Supabase]" >> "$REPORT_FILE"

echo ""
cat >> "$REPORT_FILE" << EOF

## 🔧 Dependencies Check
EOF

# Check npm packages
if npm list > /dev/null 2>&1; then
    echo "✅ npm packages: OK"
    echo "✅ npm packages: OK" >> "$REPORT_FILE"
else
    echo "⚠️ npm packages: Need review"
    echo "⚠️ npm packages: Need review" >> "$REPORT_FILE"
fi

# Check Node version
NODE_VERSION=$(node --version)
echo "Node.js: $NODE_VERSION"
echo "Node.js: $NODE_VERSION" >> "$REPORT_FILE"

echo ""
cat >> "$REPORT_FILE" << EOF

## 📝 Next Actions
EOF

echo "✅ Session checklist complete"
echo "📄 Report: $REPORT_FILE"
echo ""
echo "Hermes is ready for autonomous operation 🚀"

cat >> "$REPORT_FILE" << EOF

---
✅ Generated by: hermes-checklist.sh
EOF

# Print summary
cat "$REPORT_FILE"
